# Server configuration properties.
server:
  port: 9090

# Database configuration properties.
birds:
  datasource:
    sql:
      mysql:
        host: localhost
        port: 3306
        username: root
        password: 123456professor?
        database: birds_test
        type: mysql
  authorization:
    token:
      secret: Password!23#
      expiresIn: 10
  otp:
    expiresIn: 10*min
    length: 4
  hash:
    passwordHashStrength: 10
  user: # change
    password:
      reset:
        expiresIn: 1
  baseUrl: http://localhost:9090

oauth2:
  google:
    clientId: 444371298128-c3gjj9oprig4lt082us75ibqeun8bb1u.apps.googleusercontent.com
    clientSecret: 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
    projectId: birds-e-learning
    authProviderCertUrl: https://www.googleapis.com/oauth2/v1/certs
    redirectUrl: http://localhost:8085/user/oauth2/consent-signup
    authUrl: https://accounts.google.com/o/oauth2/auth
    tokenUrl: https://oauth2.googleapis.com/token
    defaultScopes: email%20profile%20openid
    responseType: code
    grantType: authorization_code
    userProfileUrl: https://www.googleapis.com/oauth2/v1/userinfo
    accessType: offline
    approvalPrompt: force
  internalPassword: xbiti6p5TIVkn4OTFgk3u6S6qH8d7NGSwm92F4AWS5eUlSFbmZfgOxPglsekHJgb06vpceGC6Vy//MNIu/zxxDJTLTlJ

mail:
  username: admin@blns.dgtechltd.com
  password: Ovisco76!0#
  incomingServer: http://blns.dgtechltd.com
  imapPort: 993
  pop3Port: 995
  outgoingServer: http://blns.dgtechltd.com
  smtpPort: 465
  name: http://blns.dgtechltd.com
  host: blns.dgtechltd.com
  from: blns.dgtechltd.com@gmail.com
  otp:
    subject: Birds-E-Learning signup email verification
