export declare enum Performer {
    SYSTEM = "SYSTEM",
    USER = "USER",
    OAUTH_PROVIDER_GOOGLE = "OAUTH_PROVIDER_GOOGLE",
    OAUTH_PROVIDER_FACEBOOK = "OAUTH_PROVIDER_FACEBOOK",
    OAUTH_PROVIDER_APPLE = "OAUTH_PROVIDER_APPLE"
}
